### ISSUE TITLE
Debian 11 / ruby 2.7 - Segfault with 0.5.3 mysql2 gem

### ISSUE THREAD

**Issue by RusHiiii** [brianmario/mysql2#1231] opened 2021-12-14 14:47 UTC
Hello,
I am upgrading different project from debian 10 to debian 11, with mysql2 0.5.3 gem. I am using CINC (like Chef infra) to bootrap my machine. With debian 10 everything works fine but with debian 11 I am experiencing a Segfault.

![image](https://user-images.githubusercontent.com/31767704/146020279-387d0e45-9467-437c-98ac-6f66f4f7b4bf.png)

Do you know if this gem is compatible with debian 11 ?

Thanks

**Comment by sodabrew** [comment] 2021-12-15 00:12
Expected to work fine on Debian 11. Looks like going through the standard motions on debugging will be helpful here. Can you get a backtrace from the Ruby process?

**Comment by rottenbytes** [comment] 2022-06-30 13:30
This is not specifc to the gem, I am experimenting it on debian 11 and ruby 3.0. I tested chef client from versions 16 to 18

Did you find a workaround @RusHiiii ?

**Comment by pszyszkowski** [comment] 2022-12-27 14:51
It worked for me when compiled mysql 5.7 from source
`mkdir bld ; cd bld ; cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql-5.7.40/ -DDOWNLOAD_BOOST=1 -DWITH_BOOST=boost -fPIC .. &&
make && sudo make install`
and reinstalled gem:
`gem install mysql2 -v '0.5.3' -- --with-mysql-dir=/usr/local/mysql-5.7.40/`

**Comment by sodabrew** [comment] 2022-12-28 01:39
Closing out as the original issue is not reproduced.

**Closed by sodabrew** 2022-12-28 01:39 UTC
