### ISSUE TITLE
MySQL2 fails with Rails 6

### ISSUE THREAD

**Issue by denaliai-dev** [brianmario/mysql2#1057] opened 2019-07-30 18:29 UTC
```
    OS: MacOS Mojave version 10.14.5
    MySQL 8 Server installed on Mac
    Rails 6.0.rc2
    Ruby 2.6.3
    IDE: RubyMine 2019.2 (supports Rails 6 & Ruby up to 2.7)
    
```

I am trying to build a sample application. From the IDE, I crated a new project, and selected MySQL as the DB. The IDE generated the following Gemfile:

```
    source 'https://rubygems.org'
    git_source(:github) { |repo| "https://github.com/#{repo}.git" }
    ruby '2.6.3'
    gem 'rails', '~> 6.0.0.rc2'
    gem 'mysql2', '>= 0.4.4'
    gem 'puma', '~> 3.11'
    gem 'sass-rails', '~> 5'
    gem 'webpacker', '~> 4.0'
    gem 'turbolinks', '~> 5'
    gem 'jbuilder', '~> 2.7'
    gem 'bootsnap', '>= 1.4.2', require: false
    group :development, :test do
      gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
    end
    group :development do
      gem 'web-console', '>= 3.3.0'
      gem 'listen', '>= 3.0.5', '< 3.2'
      gem 'spring'
      gem 'spring-watcher-listen', '~> 2.0.0'
    end
    group :test do
      gem 'capybara', '>= 2.15'
      gem 'selenium-webdriver'
      gem 'webdrivers'
    end
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

After the IDE generated the application, I tried doing a Bundle Install, but I am getting the following error message:

```
    Error:[rake --tasks] rake aborted!
    LoadError: dlopen(/Users/eastsidedev/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle, 9): Library not loaded: libssl.1.0.0.dylib
    Referenced from: /Users/eastsidedev/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle
    Reason: image not found - /Users/eastsidedev/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle
```

I checked, and 

`    /Users/eastsidedev/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/mysql2.bundle`

exists.

Any ideas?

**Comment by sodabrew** [comment] 2019-07-30 20:43
The problem is not that the bundle file does not exist, the problem is that `libssl.1.0.0.dylib` cannot be found. These suggestion directions are good (though not yet merged into the README) https://github.com/brianmario/mysql2/pull/1051/files

**Comment by denaliai-dev** [comment] 2019-08-06 22:32
I tried the suggestions, but the problem is still there

**Comment by breisig** [comment] 2019-08-19 19:01
Rails 6 has been released and this is a BIG issue.

**Comment by breisig** [comment] 2019-10-21 16:13
Any update?

**Comment by denaliai-dev** [comment] 2019-10-21 17:14
I went back to Rails 5.2.3. Rails 6 is now released, so I may try it again for another project.

**Comment by sodabrew** [comment] 2019-10-21 19:20
I don't understand what Rails 6 has to do with the SSL library issue?

**Comment by canon4ever** [comment] 2019-10-28 13:44
I have the same problem. I tried the suggestions, but the problem is still there too.
so , I used mariadb instead of mysql 8

![image](https://user-images.githubusercontent.com/6733303/67683029-8c5b9400-f9cb-11e9-90b4-044ff201d74e.png)

## 1、please stop or uninstall mysql first

## 2、install mariadb

```
brew install mariadb
mysql.server start
```

## 3、reset root password

```
sudo mysql_secure_installation
```

![image](https://user-images.githubusercontent.com/6733303/67682919-5dddb900-f9cb-11e9-87e6-6a3801b02714.png)

## 4、reinstall mysql2 gem

```
gem uninstall mysql2
gem install mysql2
```

this solve the problem, it works good for me.

**Comment by pidanjun** [comment] 2019-11-10 03:24
Rails 6 & MySQL 8.0.18

```sh
gem uninstall mysql2
brew install openssl
gem install mysql2 -- --with-opt-dir="$(brew --prefix openssl)"
```

solve the problem

**Closed** 2019-11-27 08:12 UTC

**Comment by bpaysen** [comment] 2020-02-22 00:29
This suggestion also solved the issue with the same error
Mac OSX, with Catalina 10.15.3, running mysql 8.0.19, using Rails 5.2 (for what its worth) and already had openssl 1.1.1d installed with Homebrew.

```
gem uninstall mysql2
brew upgrade openssl
gem install mysql2 -- --with-opt-dir="$(brew --prefix openssl)"
```

Thanks!

**Comment by dogweather** [comment] 2020-05-24 03:53
Holy cow, could someone give an explanation why this periodically breaks, and requires special work like this?

**Comment by jeremy** [comment] 2020-05-26 17:57
This happens because Homebrew now automatically uninstalls old packages after 30 days, including common dependencies like OpenSSL, MySQL, PostgreSQL, and Readline. It doesn't know that your RubyGems may depend on them.

Similar issue with ruby-build. Homebrew-managed shared libraries, like OpenSSL, are yanked out from under your Ruby install and Ruby mysteriously breaks.

To fix this, [disable auto-cleanup in Homebrew](https://docs.brew.sh/FAQ#how-do-i-uninstall-old-versions-of-a-formula). Set the `HOMEBREW_NO_INSTALL_CLEANUP=1` environment variable in your shell `~/.profile`:
```bash
export HOMEBREW_NO_INSTALL_CLEANUP=1
```

**Comment by dogweather** [comment] 2020-05-26 22:09
Thanks @jeremy !
