### ISSUE TITLE
uninitialized constant Mysql2::Client::SECURE_CONNECTION

### ISSUE THREAD

**Issue by JohnMerlino1** [brianmario/mysql2#754] opened 2016-05-11 20:30 UTC
I ran the following command on OSX 10.9.5:

brew update && brew upgrade && brew install imagemagick

Since that point, rails server and rails console raises errors.

Below is the first few lines of the error:

Users/donato/.rvm/gems/ruby-2.1.2@core/gems/mysql2-0.3.16/lib/mysql2/client.rb:12:in `<class:Client>': uninitialized constant Mysql2::Client::SECURE_CONNECTION (NameError)
    from /Users/donato/.rvm/gems/ruby-2.1.2@core/gems/mysql2-0.3.16/lib/mysql2/client.rb:2:in `<module:Mysql2>'
    from /Users/donato/.rvm/gems/ruby-2.1.2@core/gems/mysql2-0.3.16/lib/mysql2/client.rb:1:in `<top (required)>'
    from /Users/donato/.rvm/gems/ruby-2.1.2@core/gems/mysql2-0.3.16/lib/mysql2.rb:10:in `require'
    from /Users/donato/.rvm/gems/ruby-2.1.2@core/gems/mysql2-0.3.16/lib/mysql2.rb:10:in `<top (required)>'

This is the mysql gem I am using (which was working fine until the brew update):
gem 'mysql2', '0.3.16'

How can I resolve this?

**Comment by jeremy** [comment] 2016-05-11 20:48
Duplicate of #603.

(When you did a brew update, you upgraded MySQL. Now upgrade the mysql2 library to support it.)

**Comment by JohnMerlino1** [comment] 2016-05-11 21:16
It seems the issue went away when upgrading the mysql2 gem to 0.3.18. When I updated it to latest version, I got a gemload error, and I assume the latest version is only compatible with Rails 5, whereas I am using Rails 4:

http://stackoverflow.com/questions/32457657/rails-4-gemloaderror-specified-mysql2-for-database-adapter-but-the-gem-i

**Closed** 2016-05-11 21:17 UTC

**Comment by sodabrew** [comment] 2016-05-11 21:56
This particular issue for supporting MySQL 5.7 was added in 0.3.17 and higher.

As for mysql2 0.3.x / 0.4.x, here's the compatibility table for Rails and mysql2 versions: https://github.com/brianmario/mysql2/blob/master/README.md#compatibility

**Comment by deepakmahakale** [comment] 2017-04-04 16:59
Changing the version to `~> 0.3.21` fixed it for me

```ruby
gem 'mysql2', '~> 0.3.21'
```

**Comment by kroim** [comment] 2019-11-01 17:45
gem 'mysql2', '~> 0.3.21'

This worked for me as well.

**Comment by Kulgar** [comment] 2020-05-12 17:24
And here too 
rails = 3.2.12, ruby = 1.8.7 (yeah, very old project...)

**Comment by deepakmahakale** [comment] 2020-05-12 20:46
@kroim @Kulgar 
You gotta upgrade those apps  :smile:

**Comment by Kulgar** [comment] 2020-05-12 21:31
@deepakmahakale : yeah... I've just got that one into my hands, I even didn't know it was using a ruby that old until today... :-/
