### ISSUE TITLE
Ruby deprecation warning: rb_tainted_str_new_cstr

### ISSUE THREAD

**Issue by jasonperrone** [brianmario/mysql2#1232] opened 2021-12-16 16:52 UTC
/home/jason/.rvm/gems/ruby-3.0.3@upgrade_rails/gems/mysql2-0.5.3/lib/mysql2/client.rb:131: warning: rb_tainted_str_new_cstr is deprecated and will be removed in Ruby 3.2

This is at runtime, not compile time.

**Comment by BrianHawley** [comment] 2022-01-06 00:03
This seems to be a duplicate of #1137, which was fixed, but the code with the fix hasn't been released yet. See #1179 for details.

**Comment by tenderlove** [comment] 2022-05-11 20:50
Fixed in 785969fbceadd96d495ec9fecc67efee03d0056c

**Closed by tenderlove** 2022-05-11 20:50 UTC
