### ISSUE TITLE
skip-ssl option?

### ISSUE THREAD

**Issue by geremyCohen** [brianmario/mysql2#748] opened 2016-04-11 03:44 UTC
In the mysql commandline client, there is an option named --skip-ssl that disables SSL altogether.  Does the gem support this option?

Thanks,
geremy

**Comment by sodabrew** [comment] 2016-04-22 18:13
If you provide no SSL options, then the gem will not enable SSL. There isn't an explicit skip-ssl option at this time.

**Comment by geremyCohen** [comment] 2016-04-22 18:24
@sodabrew can you explain this behavior then? (ie, if by not providing any SSL options, I still get an SSL error?)

http://stackoverflow.com/questions/36527850/disabling-ssl-with-mysql2-gem

**Comment by sodabrew** [comment] 2016-04-22 20:20
What version of MySQL are you using?

Do you have SSL options specified in a /etc/my.cnf (exact location of this file depends on your local system)?

**Comment by geremyCohen** [comment] 2016-04-22 21:25
I'm on Linux, and I recently re-installed my MySQL config, so if I do have an /etc/my.cnf, its probably been reduced to a non-functional default.  Whats your angle?

**Comment by sodabrew** [comment] 2016-04-22 22:20
If you have MySQL 5.7 it may be trying to make an SSL connection by default, or if the my.cnf has a client config section it may be adding these options at run time.

**Comment by carolfly86** [comment] 2016-05-13 16:00
I'm facing the same problem. But I have verified in my /etc/my.cnf I have  ssl=FALSE in client group. And connect to the server using mysqlworkbench and mysql command line seems to be working.  The mysql server version I'm trying to connect is 5.6.

Is there a work around for this issue?

**Comment by carolfly86** [comment] 2016-05-13 16:34
@geremyCohen  if you're still facing the issue. I think this might related to a bug in mysql 5.7. I uninstalled mysql client on my laptop with 'brew uninstall mysql' and reinstalled 5.6 version mysql with brew. and then reinstalled mysql2 gem which seems to fixed the issue.

**Comment by geremyCohen** [comment] 2016-05-13 16:38
@carolfly86 wow, thanks!  So to be clear, I am on Linux against Google Cloud MySQL.  So I have little control over the server-version, however, just to clarify, by downgrading only the client you were able to remediate the issue?

**Comment by carolfly86** [comment] 2016-05-13 17:14
@geremyCohen yes, I only downgraded my client version to 5.6. The server I'm connecting to is on amazon rds which I had no control either.

**Comment by sodabrew** [comment] 2016-05-16 04:02
@carolfly86 if you suspect a bug in MySQL 5.7 related to SSL connections, could you describe the bug you think you're seeing, and check if it exists in the MySQL bug tracker?

I'm pretty sure you're seeing that MySQL 5.7 client tries to make an SSL connection by default. It's not a bug, but if your server has SSL enabled and you don't provide the certificates on the client end, it'll fail.

**Comment by sodabrew** [comment] 2018-03-19 23:33
Resolved by #793

**Closed by sodabrew** 2018-03-19 23:33 UTC
